---
name: test

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# (none)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (none)

on:
- push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.9"
        - "3.10"
        - "3.11"

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
        pip install -r requirements.txt
    - name: Static analysis
      run: |
        black .
    - name: Unit test
      run: |
        coverage run -m pytest -v -m unit --strict-markers
        coverage report -m
